### ISSUE TITLE
jsreport.Embedded 1.0.3.0 nodejs error

### ISSUE THREAD

**Issue by jigneshpanchal22** [jsreport/net#25]
@pofider 

getting below error when application starts.
Application Start code:

EmbeddedReportingServer = new EmbeddedReportingServer()
            {
                RelativePathToServer = "../App_Data"
            };
            EmbeddedReportingServer.StartAsync().Wait();

Failed to start jsreport server, output: jsreportTest\App_Data\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\async.js:17:14)
2017-08-12T10:16:03.250Z -  [31merror [39m: Error occured during reporter init Error: Unsupported store provider fs
    at DocumentStore.init (C:\jsreportTest\App_Data\node_modules\jsreport-core\lib\store\documentStore.js:37:11)
    at ensureStarted.then.then.then.then.then.then.self.initializeListeners.fire.then.self.extensionsManager.recipes.push.name (C:\jsreportTest\App_Data\node_modules\jsreport-core\lib\reporter.js:108:33)
    at tryCatcher (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\jsreportTest\App_Data\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises

**Comment by pofider** [comment]
we've released new sdk v2 and deprecating this repository in its favor. More info here

https://github.com/jsreport/jsreport-dotnet
https://jsreport.net/learn/dotnet

In particular v2 includes `jsreport.Embedded` successor with much streamlined installation. More info here https://jsreport.net/learn/dotnet-local 
I apologize for the long missing response here.
