### ISSUE TITLE
ECONNREFUSED for first rendering in embedded

### ISSUE THREAD

**Issue by pofider** [jsreport/net#9]
Details here: 

https://groups.google.com/forum/#!topic/jsreport/qnquCmX_lYk

**Comment by paulodiogo** [comment]
the trace from log folder:
2015-07-14T18:28:00.916Z - error: Error during processing request: http://localhost:2099/api/report details: Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
From previous event:
    at Reporter.render (***\App_Data\jsreport-net-embedded\lib\reporter.js:142:8)
    at ***\App_Data\jsreport-net-embedded\extension\express\lib\routes.js:138:18
    at Layer.handle [as handle_request] (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\layer.js:82:5)
    at next (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\layer.js:82:5)
    at ***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:321:12)
    at next (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:261:10)
    at serveStatic (***\App_Data\jsreport-net-embedded\node_modules\serve-static\index.js:59:14)
    at Layer.handle [as handle_request] (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:302:13)
    at ***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (***\App_Data\jsreport-net-embedded\node_modules\express\lib\router\index.js:321:12)

**Comment by pofider** [comment]
This should be fixed in the nuget 0.8.1. Feel free to reopen if you have still issues with it.
